export let config = {
    valueTypes: [
        "BigSmall",
        "UpDown",
        "LeftRight",
        "ForwBack",
        "Scale",
        "Rotate",
        "Color",
        "Hue",
        "Length",
        "Shape",
        "Height",
        "Saturation",
        "Shading",
        "Reflect",
        "None",
    ],
    valueNames: [
        "大小",
        "上下",
        "左右",
        "前后",
        "缩放",
        "旋转",
        "Color",
        "Hue",
        "Length",
        "Shape",
        "Height",
        "Saturation",
        "Shading",
        "Reflect",
        "None",
    ]
};